### ISSUE TITLE
Why event.stopPropagation?

### ISSUE THREAD

**Issue by samselikoff** [RSSchermer/ember-rl-dropdown#12]
I wanted to put a file upload label in my dropdown list

```js
{{#rl-dropdown tagName="ul"}}
  <li class='rl-dropdown-item'>
    <label>
      Upload new video
      <input type="file" style="visibility: hidden">
    </label>
  </li>
  ...
```

but this wasn't working because `rl-dropdown` [doesn't propagate events](https://github.com/RSSchermer/ember-rl-dropdown/blob/master/addon/components/rl-dropdown.js#L31). I had to copy + paste `rl-dropdown` into my project + remove this line to get it working.

Do you recall why?

**Comment by RSSchermer** [comment]
The reason for that line were #2 and #4. In hindsight though, I think flat out prevention of event propagation may not be the right solution. I think the solution is to make it configurable with a `propagateClicks` attribute. The question is, should the default value be `true` or `false`. I think I'd personally prefer `true` as the default, even though that would be a minor BC break.

@gutschik  thoughts?

**Comment by samselikoff** [comment]
Just as easy either way, I tend to prefer BC but up to you! :)

**Comment by gutschik** [comment]
go ahead and BC :)
In my case it would be refactored pretty quickly.

**Comment by RSSchermer** [comment]
Thanks for the quick feedback! I'll see if I can push out a new version tonight.

**Comment by RSSchermer** [comment]
I just publish 0.5.0 which allows the click events on the `rl-dropdown-toggle` and `rl-dropdown` components to propagate by default. Propagation can be prevented by setting `propagateClicks` to `false` on either or both components.
