### ISSUE TITLE
DEPRECATION Warning

### ISSUE THREAD

**Issue by mesbah** [RSSchermer/ember-rl-dropdown#23]
Upgraded to ember 2.18.0 and started to get this warning.

DEPRECATION: An addon is trying to access project.nodeModulesPath. This is not a reliable way to discover npm modules. Instead, consider doing: require("resolve").sync(something, { basedir: project.root }). Accessed from:   new NPMDependencyVersionChecker (node_modules\ember-rl-dropdown\node_modules\ember-cli-version-checker\src\npm-dependency-version-checker.js:11:33)

ember-cli: 2.18.0
node: 8.9.4
os: win32 x64

**Comment by RSSchermer** [comment]
Should be fixed on 0.10.2.
