### ISSUE TITLE
Keyboard events

### ISSUE THREAD

**Issue by asermax** [RSSchermer/ember-rl-dropdown#5]
I noticed this component doesn't manage keyboard events, like going up and down the dropdown with the keyboard arrows for example.

Are you planning on adding support for that? I might be able to open up a PR if you're okay with that.

**Comment by abhilashlr** [comment]
Sounds interesting. +1

**Comment by RSSchermer** [comment]
You mean going up and down the links inside an `rl-dropdown` tag?

The `rl-dropdown` component was meant to be more generic than just dropdown menus (containing just a list of links). I'm using it for example as sort a gmail-style user profile dropdown. I think making the dropdown component manage keyboard events only really makes sense for navigating lists (of links)?

So thinking about it for a bit, here's some options I could come up with:

1. Create a new component called `rl-dropdown-menu` that extends `rl-dropdown` and is specifically for lists of links.
2. Create a separate component that's specifically for navigating lists with keyboard, that doesn't really have any ties to the `rl-dropdown` component. Would look something like this:
  ```hbs
  {{#rl-dropdown-container class="dropdown"}}
    {{#rl-dropdown-toggle class="btn btn-default"}}
      Toggle <span class="caret"></span>
    {{/rl-dropdown-toggle}}

    {{#rl-dropdown class="dropdown-menu" closeOnChildClick="a:link"}}
      {{#keyboard-navigatable-list}}
        <li><a href="#">Link 1</a></li>
        <li><a href="#">Link 2</a></li>
        <li><a href="#">Link 3</a></li>
      {{/keyboard-navigatable-list}}
    {{/rl-dropdown}}
  {{/rl-dropdown-container}}
  ```
3. Create a `keyboard-navigatable` mixin. You could combine this with either of the first 2 options.

I think what might be the cleanest thing to do here, is to create a new ember addon with the `keyboard-navigatable` mixin and `keyboard-navigatable-list` component? I think the keyboard navigatability is sort of a seperate concern from the dropdown functionality, and that might be a nice way to separate them. You could then make your own `rl-dropdown-menu` in your application, simply by extending `rl-dropdown` and mixing in `keyboard-navigatable`.

There may be a better way still, curious to hear what you think!

**Comment by abhilashlr** [comment]
I guess it was about closing the drop down using 'Escape' key kinda need.

**Comment by asermax** [comment]
In my case I'm using the dropdown as a list of options for an autocompletion input component.
So I actually need both things: the `Esc` key to close the dropdown (maybe trigger a `close` action to focus back on the input?) and the arrow navigation. I'm currently extending dropdown component to add my custom logic, but thought it may be interesting to propose it here.

In any case, I like the idea of separating the navigation into a different addon, it does indeed have some other use cases apart from a dropdown, and could be easily integrated with it if needed.
As for the escape key, that should probably be addressed here, since it looks like a concern of the dropdown.

**Comment by RSSchermer** [comment]
Ah, I misunderstood, my bad. 

I'm completely on board with escape to close :+1:, definitely a dropdown concern.

Want to make a PR? I'd also be happy to look into it myself, but it may take me a couple of days to get around to it.

**Comment by asermax** [comment]
I was kinda vague on my description, I meant keyboard events in general, didn't sit to analyse which were actually concern of the component until you clarified the goal, so sorry about that :P

I'll see if I can work on a PR today or tomorrow, I'll let you know in any case :+1:

**Comment by asermax** [comment]
Started working on this but got kinda stuck on the testing; I can't make the fake key events work with the handler.
Will try to give it another look when I have some time; feel free to work on the issue if you want :+1:

**Comment by RSSchermer** [comment]
Hitting Escape should close the dropdown as of 0.3.x.

Let me know if it works for you!

**Comment by asermax** [comment]
Seems to be working, thanks!
