### ISSUE TITLE
Doesn't work on Ember 1.13 beta 1

### ISSUE THREAD

**Issue by mjanda** [RSSchermer/ember-rl-dropdown#6]
toggleDropdown action isn't received in rl-dropdown-container, so the dropdown won't open.

Unconsumed actions don't throw any error in components, so I'm not sure where it ends. In the meantime, I've made it work by replacing this.sendAction(); in rl-dropdown-toggle.js with manually toggling the dropdownExpanded property on parentView. That at least allows me to open dropdowns, but leaves other problems (navigating away from current route with expanded dropdown keeps dropdownExpanded enabled for all dropdowns everywhere else in the application etc.). Not sure if the problem is in new Ember, e-r-d or my workaround.

**Comment by RSSchermer** [comment]
Hmm, that's odd. I thought the way it's set up now was fairly idiomatic Ember, so it'd surprise me if they'd break that. I'll have to set up a test app with 1.13 and play around with it, but that may have to wait till this weekend (thesis is eating a lot of my time at the moment :expressionless:). If you happen to stumble upon an explanation, please let me know!

**Comment by mjanda** [comment]
Not sure what changed but latest canary seems to work ok, so closing this.

Good luck with yout thesis :four_leaf_clover:

**Comment by RSSchermer** [comment]
Thanks a lot!
