### ISSUE TITLE
problem with checkbox inside dropdown since 0.2.2

### ISSUE THREAD

**Issue by rafal-brize** [RSSchermer/ember-rl-dropdown#7]
I am having problems with checking checkbox with ember 1.11.3.
It happened after updating from 0.2.1 to 0.2.2

This is directly from readme, only changed link to a checkbox.
This must be related with the click event that was changed in 0.2.2

```
    {{#rl-dropdown-container class="dropdown"}}
      {{#rl-dropdown-toggle class="btn btn-default"}}
        Toggle <span class="caret"></span>
      {{/rl-dropdown-toggle}}
      {{#rl-dropdown tagName="ul" class="dropdown-menu" closeOnChildClick="a:link"}}
        {{input type="checkbox" checked=checked}}
      {{/rl-dropdown}}
    {{/rl-dropdown-container}}
```

Cheers!

**Comment by RSSchermer** [comment]
Thanks, for the bug report! I'll look into it.

Is the problem that the dropdown closes when you try to click the checkbox, or wont the checkbox check/uncheck when clicked?

**Comment by rafal-brize** [comment]
The second thing

**Comment by RSSchermer** [comment]
Should be fixed in 0.3.2, let me know if it now works for you!

@gutschik This changes the way event bubbling is prevented. It *should* still have the same effect as what you implemented in your PRs. Let me know if it breaks things for you.

**Comment by rafal-brize** [comment]
Thanks!
It is working now :+1:

**Comment by gutschik** [comment]
@RSSchermer still works like a charm ;)
